Added new file

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -17,26 +17,26 @@ jobs:
           fetch-depth: 0
 
       - name: Check file sizes
-        run : | 
-          echo " Checking changed files..."
+        run: |
+          echo "Checking changed files..."
 
           FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
 
           LIMIT=1048576
 
           for file in $FILES; do
-          if [ -f "$file" ]; then
-            SIZE=$(stat -c%s "$file")
-            echo "$file : $SIZE bytes"
+            if [ -f "$file" ]; then
+              SIZE=$(stat -c%s "$file")
+              echo "$file : $SIZE bytes"
 
-            if [ "$SIZE" -gt "$LIMIT" ]; then
-              echo "❌ ERROR: $file is larger than 1 MB."
-              exit 1
+              if [ "$SIZE" -gt "$LIMIT" ]; then
+                echo "❌ ERROR: $file is larger than 1 MB."
+                exit 1
+              fi
             fi
-          fi
-       done
+          done
 
-         echo "✅ All files are within the size limit."
+          echo "✅ All files are within the size limit."
 
   branch-name-check:
     name: Branch Name Check
@@ -46,18 +46,19 @@ jobs:
       - name: Validate branch name
         run: |
           BRANCH="${{ github.head_ref }}"
-        echo "Branch Name: $BRANCH"
 
-        if [[ "$BRANCH" =~ ^feature/.*$ || "$BRANCH" =~ ^fix/.*$ || "$BRANCH" =~ ^docs/.*$ ]]; then
-          echo "✅ Valid branch name."
-        else
-          echo "❌ Invalid branch name!"
-          echo "Branch names must start with:"
-          echo "  feature/"
-          echo "  fix/"
-          echo "  docs/"
-          exit 1
-        fi
+          echo "Branch Name: $BRANCH"
+
+          if [[ "$BRANCH" =~ ^feature/.*$ || "$BRANCH" =~ ^fix/.*$ || "$BRANCH" =~ ^docs/.*$ ]]; then
+            echo "✅ Valid branch name."
+          else
+            echo "❌ Invalid branch name!"
+            echo "Branch names must start with:"
+            echo "  feature/"
+            echo "  fix/"
+            echo "  docs/"
+            exit 1
+          fi
 
   pr-body-check:
     name: PR Body Check
